--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/EasyForms
build-by-default: true
branches:
  - master
  - php7.4
projects:
  libEasyUI:
    path: ""
    model: virion
    type: library
...
